export const FAKE_POPULAR = [
  {
    backdrop_path: "/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg",
    first_air_date: "2023-02-13",
    genre_ids: [10759, 35, 18],
    id: 215803,
    name: "Batang Quiapo. Hoping to earn the affection of his parents",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Batang Quiapo",
    overview:
      "A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.",
    popularity: 906.58,
    poster_path: "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
    vote_average: 9.8,
    vote_count: 14,
  },
];

export const FAKE_RECOMENDATION = [
  {
    adult: false,
    backdrop_path: "/l1pYrc9Qgc74JaIfMKVHiaQNvJJ.jpg",
    id: 208684,
    name: "Teen Clash",
    original_language: "tl",
    original_name: "Teen Clash",
    overview:
      "An aspiring musician who is bent on joining her school's music jam in hopes of redeeming herself from a past embarrassment meets a charming songwriter who will help her overcome the struggles in her journey.",
    poster_path: "/9EUEu3qq9AR3luAeefBPRgIQs8o.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 34.378,
    first_air_date: "2023-03-17",
    vote_average: 8,
    vote_count: 1,
    origin_country: ["PH"],
  },
  {
    adult: false,
    backdrop_path: "/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg",
    id: 65930,
    name: "My Hero Academia",
    original_language: "ja",
    original_name: "僕のヒーローアカデミア",
    overview:
      "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
    poster_path: "/ivOLM47yJt90P19RH1NvJrAJz9F.jpg",
    media_type: "tv",
    genre_ids: [10759, 16],
    popularity: 42.975,
    first_air_date: "2016-04-03",
    vote_average: 8.698,
    vote_count: 4331,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/3HR0p12DxQjj3l9OXo4wvcaJiT0.jpg",
    id: 61670,
    name: "Healer",
    original_language: "ko",
    original_name: "힐러",
    overview:
      "Kim Moon Ho is a successful reporter at a mainstream news station, but when he stumbles upon a 10-year-old mystery, he's forced to dive into a subversive underground news agency. On his journey to break open the case, Moon Ho teams up with Chae Young Shin, a second rate tabloid writer, and Healer, a mysterious internet-based journalist. With his career and his safety on the line, who can Moon Ho trust in a world full of unreliable sources? ",
    poster_path: "/too4Zig9bDJOfvnFfU1SaxKmGlR.jpg",
    media_type: "tv",
    genre_ids: [35, 10759, 9648, 18],
    popularity: 30.709,
    first_air_date: "2014-12-08",
    vote_average: 8.45,
    vote_count: 240,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/nJP1eiOjjeDdjpRReZVCsCois59.jpg",
    id: 70813,
    name: "Fight For My Way",
    original_language: "ko",
    original_name: "쌈 마이웨이",
    overview:
      "Ko Dong Man, a former taekwondo champion, and Choi Ae Ra, a receptionist, struggle to follow their dreams as life throws obstacles in their path.",
    poster_path: "/55w33JzFKBkz1evjBjqeF0enDd1.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 18.609,
    first_air_date: "2017-05-22",
    vote_average: 7.835,
    vote_count: 79,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/asVatKAwDD1N5cx3v3GZkzdeVh0.jpg",
    id: 48462,
    name: "The Heirs",
    original_language: "ko",
    original_name: "상속자들",
    overview:
      "After a chance encounter in LA, two teens from different social backgrounds reunite at an exclusive high school attended by Korea's über rich.",
    poster_path: "/n4RX9QVXjHbMB31TDWqqRLjshgu.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 31.325,
    first_air_date: "2013-10-09",
    vote_average: 7.791,
    vote_count: 539,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/kKlzA0owtx63wxpiYxgzSXrx6yz.jpg",
    id: 79434,
    name: "What's Wrong with Secretary Kim",
    original_language: "ko",
    original_name: "김비서가 왜 그럴까",
    overview:
      "Lee Young-Joon's family runs a large company and he works as the vice-president of the company. He is smart, rich and handsome, but he is arrogant. His secretary is Kim Mi-So. She has worked for him for years and she is perfect for him, but Kim Mi-So decides to quit her job.",
    poster_path: "/w6muIYgrx1XZFombs3N8owfgLwf.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 31.24,
    first_air_date: "2018-06-06",
    vote_average: 8.405,
    vote_count: 519,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/oPJQvS8Xyg7chAX0jQoC2smqMxv.jpg",
    id: 108284,
    name: "Tale of the Nine Tailed",
    original_language: "ko",
    original_name: "구미호뎐",
    overview:
      "A nine-tailed fox settles down in the city. A female television PD chases after the nine-tailed fox.",
    poster_path: "/jXx9vLO9bwKxl81oVQnzEH7960V.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 9648],
    popularity: 45.861,
    first_air_date: "2020-10-07",
    vote_average: 8.495,
    vote_count: 381,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/legulSo298h0xPqwQ2y1k9bSzxo.jpg",
    id: 95269,
    name: "Toilet-Bound Hanako-kun",
    original_language: "ja",
    original_name: "地縛少年花子くん",
    overview:
      "First year high school student and occultist, Nene Yashiro summons \"Hanako-san of the Toilet\" to grant her romantic wishes. She ends up Hanako's spiritual assistant, helping him destroy supernatural beings and change rumors to balance the spirit and human worlds. Along the way, Nene learns about her connection to the spirit world and the dark secrets regarding Hanako's past.",
    poster_path: "/qp2XSpNzopObSPkSAi7sujAsdh3.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 35],
    popularity: 25.19,
    first_air_date: "2020-01-10",
    vote_average: 8.638,
    vote_count: 629,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/cJKGfZHkMFtbVA4m2kwmdGk8uHp.jpg",
    id: 100,
    name: "I Am Not an Animal",
    original_language: "en",
    original_name: "I Am Not an Animal",
    overview:
      "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
    poster_path: "/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg",
    media_type: "tv",
    genre_ids: [16, 35],
    popularity: 8.574,
    first_air_date: "2004-05-10",
    vote_average: 8.6,
    vote_count: 769,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/c8dm74uPCMA27iKAR1WnHKTsI9h.jpg",
    id: 77696,
    name: "Run BTS!",
    original_language: "ko",
    original_name: "달려라 방탄!",
    overview:
      "Run BTS! is a variety web series starring BTS, broadcasting intermittent for free viewing on Weverse and YouTube, was formerly offered weekly for free viewing on V LIVE.",
    poster_path: "/guNo600nrTIIh88C9i6HFlCAhE.jpg",
    media_type: "tv",
    genre_ids: [10764],
    popularity: 34.441,
    first_air_date: "2015-08-01",
    vote_average: 8.603,
    vote_count: 320,
    origin_country: ["KR"],
  },
];
